replicaCount: 1

image:
  repository: container-registry.br-se1.magalu.cloud/poc-wif/poc-wif
  pullPolicy: IfNotPresent
  tag: v0.0.1

namespace: poc-wif
fullnameOverride: poc-wif
nameOverride: poc-wif

service:
  type: ClusterIP
  port: 80

workloadIdentity:
  enabled: true
  audience: "audience"
  tokenMountPath: /var/run/secrets/tokens
  tokenFileName: token
  tokenExpirationSeconds: 3600
  credentialsMountPath: /var/run/secrets/google-cloud
  credentialsFileName: credentials.json

envs:
  - name: GCP_PROJECT_ID
    value: "poc-worload-identity"
  - name: GCP_LOCATION
    value: "us-central1"
  - name: GCS_BUCKET_NAME
    value: "meu-bucket"
  - name: GEMINI_MODEL
    value: "gemini-2.5-flash"

serviceAccount:
  create: true
  name: serviceaccount-poc-wif
  automount: false

ingress:
  enabled: false

httpRoute:
  enabled: false

imagePullSecrets:
  - name: magalu-registry-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80