replicaCount: 1

image:
  repository: gcr.io/google.com/cloudsdktool/google-cloud-cli
  tag: alpine
  pullPolicy: IfNotPresent

command:
  - /bin/sh
  - -c

args:
  - |
    set -e

    apk add --no-cache curl jq >/dev/null

    echo "=== Validando ADC/WIF ==="
    ACCESS_TOKEN="$(gcloud auth application-default print-access-token)"
    echo "Access token gerado com sucesso"

    echo "=== Validando Cloud Storage ==="
    gcloud storage ls "gs://${GCS_BUCKET_NAME}"

    echo "=== Validando Gemini via Vertex AI ==="
    curl -s \
      -X POST \
      -H "Authorization: Bearer ${ACCESS_TOKEN}" \
      -H "Content-Type: application/json" \
      "https://${GCP_LOCATION}-aiplatform.googleapis.com/v1/projects/${GCP_PROJECT_ID}/locations/${GCP_LOCATION}/publishers/google/models/${GEMINI_MODEL}:generateContent" \
      -d '{
        "contents": [
          {
            "role": "user",
            "parts": [
              {
                "text": "Responda apenas: OK"
              }
            ]
          }
        ]
      }' | jq .

namespace: poc-wif
fullnameOverride: poc-wif
nameOverride: poc-wif

service:
  type: ClusterIP
  port: 80

workloadIdentity:
  enabled: true
  audience: "//iam.googleapis.com/projects/630729803660/locations/global/workloadIdentityPools/poc-workload-identity/providers/mgc-k8s-cluster"
  tokenMountPath: /var/run/secrets/tokens
  tokenFileName: token
  tokenExpirationSeconds: 3600
  credentialsMountPath: /var/run/secrets/google-cloud
  credentialsFileName: credentials.json

envs:
  - name: GCP_PROJECT_ID
    value: "poc-workload-identity-501203"
  - name: GCP_LOCATION
    value: "us-central1"
  - name: GCS_BUCKET_NAME
    value: "poc-wif"
  - name: GEMINI_MODEL
    value: "gemini-2.5-flash"

serviceAccount:
  create: true
  name: serviceaccount-poc-wif
  automount: false

ingress:
  enabled: false

httpRoute:
  enabled: false

imagePullSecrets:
  - name: magalu-registry-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80