apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-wif.fullname" . }}
  namespace: {{ include "chart-wif.namespace" . }}
  labels:
    {{- include "chart-wif.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart-wif.selectorLabels" . | nindent 4 }}
